GET http://localhost:8080/api/companies

###

GET http://localhost:8080/api/companies/Ontel

###

POST http://localhost:8080/api/companies
Content-Type: application/json

{
  "name": "Liddel",
  "value": 10,
  "type": "Grocery"
}

###

GET http://localhost:8080/api/companies/Liddel

###

PUT http://localhost:8080/api/companies/Liddel
Content-Type: application/json

{
  "value": 20,
  "type": "Groccerryy"
}

###

GET http://localhost:8080/api/companies/Liddel

###

GET http://localhost:8080/api/workers

###

GET http://localhost:8080/api/workers/Jan

###

POST http://localhost:8080/api/workers
Content-Type: application/json

{
  "name": "Marcin",
  "age": 10,
  "company": "Liddel"
}

###

GET http://localhost:8080/api/workers/Marcin

###

PUT http://localhost:8080/api/workers/Marcin
Content-Type: application/json

{
  "age": 50
}

###

GET http://localhost:8080/api/workers/Marcin

###

DELETE  http://localhost:8080/api/workers/Jan

###

DELETE http://localhost:8080/api/workers

###

DELETE http://localhost:8080/api/companies/Frog

###

DELETE http://localhost:8080/api/companies